import { StyleSheet } from 'react-native'
import { scaleSize, setSpText } from '../../utils'

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: 'white',
  },
  infocontainer: {
    position: 'absolute',
    // width: scaleSize(500),
    // height: scaleSize(600),
    justifyContent: 'space-around',
    alignItems: 'flex-start',
    top: '70%',
    bottom: 0,
    right: 0,
    left: 0,
    flexDirection: 'column',
    backgroundColor: 'white',
  },
  imageContainer: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F0F0F0',
    top: 0,
    right: 0,
    left: 0,
    bottom: '30%',
  },
  image: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    top: scaleSize(110),
    right: scaleSize(50),
    left: scaleSize(50),
    bottom: scaleSize(20),
  },
  classifyTitleView: {
    height: scaleSize(50),
    width: '80%',
    marginLeft: scaleSize(50),
    flexDirection: 'row',
    backgroundColor: 'transparent',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    height: scaleSize(50),
    minWidth: scaleSize(120),
    fontSize: setSpText(30),
    backgroundColor: 'transparent',
    color: '#505050',
    // textAlign: 'center',
    // paddingLeft: 5,
    textAlign: 'left',
  },
  titleConfidence: {
    height: scaleSize(50),
    minWidth: scaleSize(380),
    fontSize: setSpText(30),
    backgroundColor: 'transparent',
    color: '#505050',
    // textAlign: 'center',
    // paddingLeft: 5,
    textAlign: 'left',
  },
  edit: {
    minHeight: scaleSize(60),
    width: scaleSize(380),
    fontSize: setSpText(30),
    backgroundColor: 'transparent',
    color: '#505050',
    // borderColor: 'gray',
    // borderWidth: 1,
    padding: 0,
    paddingLeft: 2,
    borderLeftColor: 'transparent',
    borderTopColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: 'transparent',
  },
  btnSwitchModelsView: {
    height: scaleSize(70),
    width: '80%',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  txtBtnSwitchModelsView: {
    fontSize: setSpText(30),
    backgroundColor: 'transparent',
    color: 'white',
    textAlign: 'center',
  },
  DividingLine: {
    position: 'absolute',
    height: scaleSize(20),
    backgroundColor: '#A0A0A0',
    width: '100%',
    bottom: 0,
  },
})
