export default {
  SUBMIT: '执行',
  UNDO: '撤销',
  ADD_NODE: '添加节点',
  EDIT_NODE: '编辑节点',
  DELETE_NODE: '删除节点',
  REDO: '重做',
  CREATE_POLYLINE: '绘制直线',
  CREATE_POLYGON: '绘制多边形',
  DELETE: '删除',
  BREAK: '打断',
  SPLIT_REGION: '切割',
  MERGE: '合并',
  ERASE_REGION: '擦除',
  DRAWREGION_ERASE_REGION: '手绘擦除',
  DRAW_HOLLOW_REGION: '生成岛洞',
  DRAWREGION_HOLLOW_REGION: '手绘岛洞',
  FILL_HOLLOW_REGION: '填充岛洞',
  PATCH_HOLLOW_REGION: '补充岛洞',
  ATTRIBUTE: '属性',
  MODIFIED: '修改',
}