/**
 * Copyright © SuperMap. All rights reserved.
 * Author: Asort
 * https://github.com/AsortKeven
 */
export const CoordSysData = {
  Beijing54_Albers_Equal_Area: `
<sml:CoordinateReferenceSystem>
<sml:Name>Beijing54_Albers_Equal_Area</sml:Name>
<sml:Type>-1</sml:Type>
<sml:EPSGCode>0</sml:EPSGCode>
<sml:Units>METER</sml:Units>
<sml:DistUnits>METER</sml:DistUnits>
<sml:GeographicCoordinateSystem>
<sml:Name>GCS_Beijing_1954</sml:Name>
<sml:Type>4214</sml:Type>
<sml:Units>DEGREE</sml:Units>
<sml:DistUnits>METER</sml:DistUnits>
<sml:HorizontalGeodeticDatum>
<sml:Name>D_Beijing_1954</sml:Name>
<sml:Type>6214</sml:Type>
<sml:Spheroid>
<sml:Name>Krasovsky_1940</sml:Name>
<sml:Type>7024</sml:Type>
<sml:SemiMajorAxis>6378245</sml:SemiMajorAxis>
<sml:InverseFlattening>298.3</sml:InverseFlattening>
</sml:Spheroid>
</sml:HorizontalGeodeticDatum>
<sml:PrimeMeridian>
<sml:Name>Greenwich</sml:Name>
<sml:Type>8901</sml:Type>
<sml:PrimeMeridian>0</sml:PrimeMeridian>
</sml:PrimeMeridian>
</sml:GeographicCoordinateSystem>
<sml:MapProjection>
<sml:Name>Albers</sml:Name>
<sml:Type>43007</sml:Type>
</sml:MapProjection>
<sml:Parameters>
<sml:FalseEasting>0</sml:FalseEasting>
<sml:FalseNorthing>0</sml:FalseNorthing>
<sml:CentralMeridian>105</sml:CentralMeridian>
<sml:StandardParallel1>27</sml:StandardParallel1>
<sml:StandardParallel2>45</sml:StandardParallel2>
<sml:ScaleFactor>1</sml:ScaleFactor>
<sml:CentralParallel>0</sml:CentralParallel>
<sml:Azimuth>0</sml:Azimuth>
<sml:FirstPointLongitude>0</sml:FirstPointLongitude>
<sml:SecondPointLongitude>0</sml:SecondPointLongitude>
<sml:RectifiedAngle>0</sml:RectifiedAngle>
</sml:Parameters>
</sml:CoordinateReferenceSystem>
`,
  GCS_CHINA_2000: `
<sml:CoordinateReferenceSystem>
<sml:Name>GCS_China_2000</sml:Name>
<sml:Type>1</sml:Type>
<sml:EPSGCode>0</sml:EPSGCode>
<sml:Units>METER</sml:Units>
<sml:DistUnits>METER</sml:DistUnits>
<sml:GeographicCoordinateSystem>
<sml:Name>GCS_China_2000</sml:Name>
<sml:Type>37313</sml:Type>
<sml:Units>DEGREE</sml:Units>
<sml:DistUnits>METER</sml:DistUnits>
<sml:HorizontalGeodeticDatum>
<sml:Name>D_China_2000</sml:Name>
<sml:Type>39313</sml:Type>
<sml:Spheroid>
<sml:Name>China_2000</sml:Name>
<sml:Type>7044</sml:Type>
<sml:SemiMajorAxis>6378137</sml:SemiMajorAxis>
<sml:InverseFlattening>298.257222101</sml:InverseFlattening>
</sml:Spheroid>
</sml:HorizontalGeodeticDatum>
<sml:PrimeMeridian>
<sml:Name>Greenwich</sml:Name>
<sml:Type>8901</sml:Type>
<sml:PrimeMeridian>0</sml:PrimeMeridian>
</sml:PrimeMeridian>
</sml:GeographicCoordinateSystem>
<sml:MapProjection>
<sml:Name/>
<sml:Type>43000</sml:Type>
</sml:MapProjection>
<sml:Parameters>
<sml:FalseEasting>0</sml:FalseEasting>
<sml:FalseNorthing>0</sml:FalseNorthing>
<sml:CentralMeridian>0</sml:CentralMeridian>
<sml:StandardParallel1>0</sml:StandardParallel1>
<sml:StandardParallel2>0</sml:StandardParallel2>
<sml:ScaleFactor>0</sml:ScaleFactor>
<sml:CentralParallel>0</sml:CentralParallel>
<sml:Azimuth>0</sml:Azimuth>
<sml:FirstPointLongitude>0</sml:FirstPointLongitude>
<sml:SecondPointLongitude>0</sml:SecondPointLongitude>
<sml:RectifiedAngle>0</sml:RectifiedAngle>
</sml:Parameters>
</sml:CoordinateReferenceSystem>
`,
  GCS_WGS_1984: `
<sml:CoordinateReferenceSystem>
<sml:Name>GCS_WGS_1984</sml:Name>
<sml:Type>1</sml:Type>
<sml:EPSGCode>0</sml:EPSGCode>
<sml:Units>METER</sml:Units>
<sml:DistUnits>METER</sml:DistUnits>
<sml:GeographicCoordinateSystem>
<sml:Name>GCS_WGS_1984</sml:Name>
<sml:Type>4326</sml:Type>
<sml:Units>DEGREE</sml:Units>
<sml:DistUnits>METER</sml:DistUnits>
<sml:HorizontalGeodeticDatum>
<sml:Name>D_WGS_1984</sml:Name>
<sml:Type>6326</sml:Type>
<sml:Spheroid>
<sml:Name>WGS_1984</sml:Name>
<sml:Type>7030</sml:Type>
<sml:SemiMajorAxis>6378137</sml:SemiMajorAxis>
<sml:InverseFlattening>298.257223563</sml:InverseFlattening>
</sml:Spheroid>
</sml:HorizontalGeodeticDatum>
<sml:PrimeMeridian>
<sml:Name>Greenwich</sml:Name>
<sml:Type>8901</sml:Type>
<sml:PrimeMeridian>0</sml:PrimeMeridian>
</sml:PrimeMeridian>
</sml:GeographicCoordinateSystem>
<sml:MapProjection>
<sml:Name/>
<sml:Type>43000</sml:Type>
</sml:MapProjection>
<sml:Parameters>
<sml:FalseEasting>0</sml:FalseEasting>
<sml:FalseNorthing>0</sml:FalseNorthing>
<sml:CentralMeridian>0</sml:CentralMeridian>
<sml:StandardParallel1>0</sml:StandardParallel1>
<sml:StandardParallel2>0</sml:StandardParallel2>
<sml:ScaleFactor>0</sml:ScaleFactor>
<sml:CentralParallel>0</sml:CentralParallel>
<sml:Azimuth>0</sml:Azimuth>
<sml:FirstPointLongitude>0</sml:FirstPointLongitude>
<sml:SecondPointLongitude>0</sml:SecondPointLongitude>
<sml:RectifiedAngle>0</sml:RectifiedAngle>
</sml:Parameters>
</sml:CoordinateReferenceSystem>
`,
  Xi_An_1980_China: `
<sml:CoordinateReferenceSystem>
<sml:Name>Sphere Mercator</sml:Name>
<sml:Type>53004</sml:Type>
<sml:EPSGCode>0</sml:EPSGCode>
<sml:Units>METER</sml:Units>
<sml:DistUnits>METER</sml:DistUnits>
<sml:GeographicCoordinateSystem>
<sml:Name>GCS_WGS_1984</sml:Name>
<sml:Type>4326</sml:Type>
<sml:Units>DEGREE</sml:Units>
<sml:DistUnits>METER</sml:DistUnits>
<sml:HorizontalGeodeticDatum>
<sml:Name>D_WGS_1984</sml:Name>
<sml:Type>6326</sml:Type>
<sml:Spheroid>
<sml:Name>WGS_1984</sml:Name>
<sml:Type>7030</sml:Type>
<sml:SemiMajorAxis>6378137</sml:SemiMajorAxis>
<sml:InverseFlattening>298.257223563</sml:InverseFlattening>
</sml:Spheroid>
</sml:HorizontalGeodeticDatum>
<sml:PrimeMeridian>
<sml:Name>Greenwich</sml:Name>
<sml:Type>8901</sml:Type>
<sml:PrimeMeridian>0</sml:PrimeMeridian>
</sml:PrimeMeridian>
</sml:GeographicCoordinateSystem>
<sml:MapProjection>
<sml:Name>SPHERE_MERCATOR</sml:Name>
<sml:Type>43045</sml:Type>
</sml:MapProjection>
<sml:Parameters>
<sml:FalseEasting>0</sml:FalseEasting>
<sml:FalseNorthing>0</sml:FalseNorthing>
<sml:CentralMeridian>0</sml:CentralMeridian>
<sml:StandardParallel1>0</sml:StandardParallel1>
<sml:StandardParallel2>0</sml:StandardParallel2>
<sml:ScaleFactor>0.9996</sml:ScaleFactor>
<sml:CentralParallel>0</sml:CentralParallel>
<sml:Azimuth>0</sml:Azimuth>
<sml:FirstPointLongitude>0</sml:FirstPointLongitude>
<sml:SecondPointLongitude>0</sml:SecondPointLongitude>
<sml:RectifiedAngle>0</sml:RectifiedAngle>
</sml:Parameters>
</sml:CoordinateReferenceSystem>
`,
  Sphere_Mercator: `
<sml:CoordinateReferenceSystem>
<sml:Name>Xi-An 1980 China</sml:Name>
<sml:Type>1</sml:Type>
<sml:EPSGCode>0</sml:EPSGCode>
<sml:Units>METER</sml:Units>
<sml:DistUnits>METER</sml:DistUnits>
<sml:GeographicCoordinateSystem>
<sml:Name>GCS_XiAn_1980</sml:Name>
<sml:Type>37312</sml:Type>
<sml:Units>DEGREE</sml:Units>
<sml:DistUnits>METER</sml:DistUnits>
<sml:HorizontalGeodeticDatum>
<sml:Name>D_XiAn_1980</sml:Name>
<sml:Type>39312</sml:Type>
<sml:Spheroid>
<sml:Name>International_1975</sml:Name>
<sml:Type>40023</sml:Type>
<sml:SemiMajorAxis>6378140</sml:SemiMajorAxis>
<sml:InverseFlattening>298.257</sml:InverseFlattening>
</sml:Spheroid>
</sml:HorizontalGeodeticDatum>
<sml:PrimeMeridian>
<sml:Name>Greenwich</sml:Name>
<sml:Type>8901</sml:Type>
<sml:PrimeMeridian>0</sml:PrimeMeridian>
</sml:PrimeMeridian>
</sml:GeographicCoordinateSystem>
<sml:MapProjection>
<sml:Name/>
<sml:Type>43000</sml:Type>
</sml:MapProjection>
<sml:Parameters>
<sml:FalseEasting>0</sml:FalseEasting>
<sml:FalseNorthing>0</sml:FalseNorthing>
<sml:CentralMeridian>0</sml:CentralMeridian>
<sml:StandardParallel1>0</sml:StandardParallel1>
<sml:StandardParallel2>0</sml:StandardParallel2>
<sml:ScaleFactor>0</sml:ScaleFactor>
<sml:CentralParallel>0</sml:CentralParallel>
<sml:Azimuth>0</sml:Azimuth>
<sml:FirstPointLongitude>0</sml:FirstPointLongitude>
<sml:SecondPointLongitude>0</sml:SecondPointLongitude>
<sml:RectifiedAngle>0</sml:RectifiedAngle>
</sml:Parameters>
</sml:CoordinateReferenceSystem>
`,
}
