/**
 * 地图触摸事件类型
 */
export default {
  //点击监听类型
  NORMAL: 'NORMAL',
  NULL: 'NULL',
  MAP_TOOL_TAGGING: 'MAP_TOOL_TAGGING',

  SET_START_STATION: 'SET_START_STATION',
  MIDDLE_STATIONS: 'MIDDLE_STATIONS',
  SET_END_STATION: 'SET_END_STATION',
  LOCATION: 'LOCATION',
  SET_AS_START_STATION: 'SET_AS_START_STATION',
  SET_AS_END_STATION: 'SET_AS_END_STATION',
  ADD_STATIONS: 'ADD_STATIONS',
  ADD_BARRIER_NODES: 'ADD_BARRIER_NODES	',
  ADD_NODES: 'ADD_NODES',
}
