/**
 * 地图触摸事件类型
 */
export default {
  //点击监听类型
  NORMAL: 'NORMAL',
  NULL: 'NULL',
  MAP_TOOL_TAGGING: 'MAP_TOOL_TAGGING',

  // 网络分析事件
  SET_START_STATION: 'SET_START_STATION',
  MIDDLE_STATIONS: 'MIDDLE_STATIONS',
  SET_END_STATION: 'SET_END_STATION',
  LOCATION: 'LOCATION',
  SET_AS_START_STATION: 'SET_AS_START_STATION',
  SET_AS_END_STATION: 'SET_AS_END_STATION',
  ADD_STATIONS: 'ADD_STATIONS',
  ADD_BARRIER_NODES: 'ADD_BARRIER_NODES	',
  ADD_NODES: 'ADD_NODES',

  // 邻近分析
  REFERENCE: 'REFERENCE',

  //创建动画路径
  ANIMATION_WAY: 'ANIMATION_WAY',

  //导航点击监听
  NAVIGATION_TOUCH_BEGIN: 'NAVIGATION_TOUCH_BEGIN',
  NAVIGATION_TOUCH_END: 'NAVIGATION_TOUCH_END',

  //视频地图AR模式下点击
  AIMAPTOUCH: 'AIMAPTOUCH',
}
