import { StyleSheet, Platform } from 'react-native'
import { scaleSize, setSpText } from '../../utils'
import { color, zIndexLevel } from '../../styles'

export const HEADER_HEIGHT = scaleSize(88) + (Platform.OS === 'ios' ? 20 : 0)
export const HEADER_PADDINGTOP = Platform.OS === 'ios' ? 20 : 0

export default StyleSheet.create({
  defaultHeaderView: {
    width: '100%',
    paddingTop: HEADER_PADDINGTOP,
    height: HEADER_HEIGHT,
    // borderBottomWidth: 1,
    // borderBottomColor: '#e2e2e2',
    flexDirection: 'row',
    backgroundColor: '#303030',
    alignItems: 'center',
  },
  fixHeaderView: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: zIndexLevel.FOUR + 1,
    width: '100%',
    paddingTop: HEADER_PADDINGTOP,
    height: HEADER_HEIGHT,
    backgroundColor: '#303030',
    flexDirection: 'row',
    alignItems: 'center',
  },
  floatHeaderView: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: zIndexLevel.FOUR + 1,
    width: '100%',
    paddingTop: HEADER_PADDINGTOP,
    height: HEADER_HEIGHT,
    backgroundColor: '#rgba(255, 255, 255, 0)',
    flexDirection: 'row',
    alignItems: 'center',
  },
  floatNoTitleHeaderView: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100019,
    width: '100%',
    paddingTop: HEADER_PADDINGTOP,
    height: HEADER_HEIGHT,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#rgba(255, 255, 255, 0)',
  },
  navigationHeader: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backBtn: {
    position: 'absolute',
    zIndex: zIndexLevel.FOUR + 1,
    width: 60,
    padding: 5,
    marginLeft: scaleSize(20),
    justifyContent: 'center',
    // alignItems: 'flex-start',
  },
  backIcon: {
    // width: 9,
    // height: 14,
    width: scaleSize(60),
    height: scaleSize(60),
    backgroundColor: '#rgba(255, 255, 255, 0)',
    marginRight: 3,
  },
  iconBtnBg: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconBtnBgDarkColor: {
    backgroundColor: '#rgba(0, 0, 0, 0.6)',
  },
  headerLeftView: {
    position: 'absolute',
    zIndex: zIndexLevel.FOUR + 1,
    width: 60,
    // padding: 5,
    marginLeft: scaleSize(35),
    alignItems: 'flex-start',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    flexDirection: 'row',
  },
  headerRightView: {
    position: 'absolute',
    zIndex: zIndexLevel.FOUR + 1,
    height: scaleSize(60),
    alignItems: 'center',
    // justifyContent: 'space-around',
    justifyContent: 'center',
    flexDirection: 'row',
    right: scaleSize(25),
    // backgroundColor: 'transparent',
    // backgroundColor:"red",
  },
  headerTitleView: {
    position: 'absolute',
    zIndex: -1,
    left: scaleSize(80),
    right: scaleSize(80),
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    // fontSize: 18,
    // color: '#222222',
    color: 'white',
    fontSize: setSpText(36),
    // fontWeight: 'bold',
    backgroundColor: 'rgba(255, 255, 255, 0)',
  },
  subTitle: {
    color: color.gray3,
    fontSize: setSpText(20),
    // fontWeight: 'bold',
  },
  count: {
    position: 'absolute',
    color: '#fa575c',
    left: 38,
  },
})
